### ISSUE TITLE
yarn as replacement for npm... 

### ISSUE THREAD

**Issue by g0ld3lux** [codecasts/ambientum#12]
i dont know if you already have the yarn package manager or just the npm...
but i have it locally available so i know when i run the yarn install ... its my local installation of yarn...
not the one that i source out using the command.bash

It would be Great if we can use this as a container where we can save all our local packages dependencies...
rather than downloading over again and again dependencies using npm install..

The Idea is to Save All The Depencies in a volume... that can be persist using yarn commands....
so when ever we destroy the containers all dependencies  that we change will remain the same...

This will give a Boost in developing locally i hope you take this into consideration thanks

**Comment by g0ld3lux** [comment]
There is a package here that does what i was telling at this thread...

```
https://hackernoon.com/using-yarn-with-docker-c116ad289d56#.txtqjb8yp
```

If we can implement this in this repo , this would be awesome

**Comment by hernandev** [comment]
Yarn support, since it is not pure JS, is gonna be included soon.

Keeping this open until included

**Comment by hernandev** [comment]
Yarn support just added @g0ld3lux.

You are encouraged to upgrade the node images and download a new alias file.

since now. you can use all comands with prefixes, so it does not interfere with local existing tools.

Examples:

When node related:

`n yarn global add vue`
`n vue --version`

`n yarn global add gulp`
`n gulp`

`n npm run task`

When PHP Related

```
p composer --version
p composer global require php-cs-fixer
p php-cs-fixer
```
:)
