### ISSUE TITLE
Is that possible to put supervisord on the PHP Container?

### ISSUE THREAD

**Issue by caiquecastro** [codecasts/ambientum#20]
I don't know if it's suitable to put supervisor on container images, is it?

Sorry the lack of further knowledge on the subject.

**Comment by zabaala** [comment]
@caiquecastro Acho que não seria. 

Eu já fiz isso. O problema é que precisei alterar um pouco as configurações. Mas dá sim!

**Comment by hernandev** [comment]
Não, o processo quando cai, o container deve cair junto.

Cada container preferencialmente deve conter 1 processo, no caso do PHP flexibilizamos pra rodar o FPM + Servidor web Juntos, mas ambos são gerenciados pelo `tini`.

Se você precisa que um container volte a rodar caso caia, adicione a opção

`--restart=always` na linha de comando ou
```
   restart: 'always'
```
no docker compose

**Comment by zabaala** [comment]
@hernandev mas se houver a necessidade de rodar alguns outros serviços/comandos no container, seria uma "má prática" utilizar o supervisor, mesmo sendo executado em nodaemon?

No meu caso precisei adicionar algumas coisas e executar alguns comandos após o build do Docker. Eu só consegui fazer com o supervisor. =/

**Comment by hernandev** [comment]
@zabaala the problem is not solved by supervisor, take in mind in your example that running the exactly same command on the terminal

`/bin/bash -c "source /etc/apache2/envvars && apache2 -D FOREGROUND"` 

would solve your problem, supervisor is made to restart anything that may be down, it supervises processes to restart them automatically.

Using supervisor on Docker is pointless.

**Comment by caiquecastro** [comment]
Thank you for the reply. I was just curious.
