### ISSUE TITLE
Alpine based images

### ISSUE THREAD

**Issue by edbizarro** [codecasts/ambientum#26]
I'm willing to create an alpine version of the images, I would like to know if there is any interest in this versions, this way the footprint will be smaller

**Comment by hernandev** [comment]
Only benefit from using alpine over Debian is the container size, not `memory consumption` or `memory footprint`.

Debian makes it easier to avoid compiling tons of software needed by most images, and by that is way easier to maintain.

One big difference is how Alpine and larger images will handle shared libraries, by either statically linking or dynamically linking those. Most larger distros will dynamically link libraries which in theory could lead to bigger memory usage, but as the containers most of the time are using 1 or 2 processes, the library loading is not a big concern, since most of the time, it has no direct affect on how much physical memory is used.

Size alone, is not a big motive to migrate to Alpine or other micro distro, since most images here are built on top of Debian. Once you download the first image, the debian base image layers (the larger and variable part that alpine would replace) gets on cache, and any downloads you will do are **only** the actual software running on it.

Alpine may be a nice to have feature in the future, but a bigger improvement that should be made first is moving PHP to compiled instead of installed from repos.

Right now, memory usage is too low already, so we can thing about those things later, and focus on the bigger issue of moving it to compiled.

**Comment by hernandev** [comment]
@edbizarro let's keep this open for a now, while we plan on migrate php to compiled, if doing so on Alpine would require less work, than we have a bigger motive to migrate

**Comment by edbizarro** [comment]
@hernandev nice! if you need any help with this i'll be happy to help

**Comment by hernandev** [comment]
@edbizarro 

Progress started on Alpine builds. check it out:

https://github.com/codecasts/ambientum/blob/php-alpine/php-alpine/7.1/Dockerfile

**Comment by edbizarro** [comment]
Nice!

I was thinking, what's the benefit from compiling PHP from source rather than using an alpine official image?

**Comment by hernandev** [comment]
@edbizarro Alpine repos not even have 7.1 yet. So, from source we have both control and faster updates

**Comment by hernandev** [comment]
@edbizarro another point is, at a given moment, let's say we found a bug a 7.0 version, but the repos for 7.0 are not available anymore, given that we're using the source, we can always compile older versions

**Comment by edbizarro** [comment]
the latest version from alpine official docker php is 7.1.2 https://hub.docker.com/_/php

**Comment by edbizarro** [comment]
yeah, that's a good point

**Comment by hernandev** [comment]
Now I've got your point. So, basically my build is a lot inspired on that, 
I've meant before about alpine repositories (apk add install) not the library PHP.

The library PHP has indeed the latest versions, but working with extensions there is kinda helish, also, check again on the script, there are plent of other stuff being made, like xdebug support, newrelic, fpm (double build on single image) and some customizations for a normal user.

The main build is similar, i've used the library scripts to build this one.

**Comment by hernandev** [comment]
Building PHP 7.1.2 CLI and Nginx images so it will be as testing this week, before we replace the old images.

Alpine builds will be 100% compatible and will not require any changes on your projects or configuration.

images name (for now for testing) are:

`ambientum/php-alpine:7.1`
`ambientum/php-alpine:7.1-nginx`

We will find out the final image sizes in a bit

**Comment by hernandev** [comment]
OK, so the primary result now is 

PHP: `64MB`
PHP with Nginx: `66MB`
PHP with Caddy: `69MB`

So, pretty good comparing to Debian version, that was `~144MB`

@pedrommone You had been also interest in this so, here it is.

---

All features are now available, like xdebug and newrelic support.

This feature now enters testing.

P.S. Apache support is being planed.

**Comment by hernandev** [comment]
Alpine images are the new default.

Uses are encouraged to pull new images and update the rc file

**Comment by pjhartin** [comment]
How do we enable xdebug?

**Comment by hernandev** [comment]
XDEBUG_ENABLED=true on the container env
