### ISSUE TITLE
Use Googles DNS instead of host

### ISSUE THREAD

**Issue by pedrommone** [codecasts/ambientum#40]

**Comment by hernandev** [comment]
1) Edit `/etc/default/docker`

2) Set the DNS you want on this line:

`DOCKER_OPTS="--dns <dns_server_1> --dns <dns_server_2>"`

**Comment by pedrommone** [comment]
@hernandev I forget that DNS is a part of Docker product. Anyway, thanks!

**Comment by hernandev** [comment]
@pedrommone anyway, even tough I personally use Google's DNS, the main problem is some people cannot access 8.8.8.8/8.8.4.4 because of company/provider policies. 

Hardcoding a DNS provider is never a good idea.

If you absolutely need this, and editing the default options of the daemon are not an option, please just do the following:

Create a resolve.conf file and mount it on container's /etc/resolve.conf

That should be enough, never actually tested it.

É nois.
