### ISSUE TITLE
Suggestion: move from **mailcatcher** to **mailhog**

### ISSUE THREAD

**Issue by rogeriopradoj** [codecasts/ambientum#69]
Hello, I'd like to know if you already thought about moving from [mailcatcher](https://mailcatcher.me/), which is based in ruby, to [mailhog](https://hub.docker.com/r/mailhog/mailhog/~/dockerfile/), an binary that is easier to install.

Maybe it could reduce disk size needed, because mailhog could be easily based in alpine instead of debian as well.

Best!

**Comment by hernandev** [comment]
That's awesome. Didn't know about MailHog. It's a dropin replacement! Thanks for the tip. I'ill take a deeper look into it on the next couple days.

**Comment by hernandev** [comment]
Forgot to update here, I've been using `mailhog` since you opened this thread, actually works pretty well as a `mailcatcher` replacement.

Fortunelly, no work is needed on our side since they keep a neat and small image available for usage.

I'm taking the decision to remove some images from ambientum and instead, include more examples on how to use official images for things like mysql and mailhog.

So we cover all aspects without having to keep building images.

At a ideal moment, ambientum will consist only of php and node images.

mailhog oficial image is: mailhog/mailhog:latest

**Comment by pedrommone** [comment]
@hernandev maybe you can replace frontend stuff with their official images? IMHO, it will be easier to maintain.

**Comment by hernandev** [comment]
@pedrommone what frontend stuff?

**Comment by pedrommone** [comment]
Containers like node, nvm...

**Comment by hernandev** [comment]
Node: no, most images are not really well configured to run on user-land, like npm hungry for sudo.

Database and stuff like mailcatcher will indeed, be preffered on official images.

the new Ambientum CLI will generate configs so using the official ones are not a problem.

**Comment by pedrommone** [comment]
Got it, looking forward to seeing the CLI! :)

Em qua, 17 de jan de 2018 às 09:01, Diego Hernandes <
notifications@github.com> escreveu:

**Comment by hernandev** [comment]
CLI discussion at https://github.com/codecasts/ambientum/issues/79

**Comment by hernandev** [comment]
So, the project took a left after this discussion, so, closing, thank you all for the help!
