### ISSUE TITLE
Why node 7 in .ambientum_rc if latest is node 8

### ISSUE THREAD

**Issue by rogeriopradoj** [codecasts/ambientum#72]
Hi

Is there a reason why why node 7 is in .ambientum_rc if latest is node 8?

Best!

**Comment by hernandev** [comment]
Yes, just wasn't updated since then.

The source files are being recreated using node that's why I haven't updated those.

**Comment by hernandev** [comment]
node images will be updated to alpine and ambientum_rc will get deprecated in favor of a new binary handled.

@vinicius73 I need you'r node / javascript knowledge to determine if node can run without locale files.

On PHP, it works well unless you need to to translate days of week in to different languages (like displaing `Domingo` instead of `Sunday`) using bundled PHP methods.

Since it's really trivial to implement this kind of things without native functions, PHP is a good candidate to run on Alpine Linux with `musl` builds instead of `glibc`.

Let me know your thoughts so we can move on building node into alpine instead of debian.

@rogeriopradoj sorry for the thread hijacking

**Comment by hernandev** [comment]
@vinicius73 @rogeriopradoj do you guys know anything about locale usage on node?

**Comment by rogeriopradoj** [comment]
> https://github.com/codecasts/ambientum/issues/72#issuecomment-355231293

Sorry but no...

**Comment by hernandev** [comment]
@rogeriopradoj I'm pretty sure they don't depend on glibc locales, they use ICU instead so that would be a nice move.

**Comment by hernandev** [comment]
Wait, I did that already, Node is already on Alpine Linux. rc file is not updated yet but you can use the images if you want to try.

**Comment by hernandev** [comment]
ambientum_rc related questions are being closed right now because of the new CLI interface being almost ready.

Thank you for supporting so much this project.
