### ISSUE TITLE
gzip on nginx?

### ISSUE THREAD

**Issue by pSchaub** [codecasts/ambientum#93]
I am not sure if this is a valid idea - maybe somebody else has more knowledge about this.

I know that "nginx" is able to do gzip compression. Would it be helpful to enable it in the nginx configuration to increase the speed of deployed apps? Or is it already enabled? Or is there a good reason to not do it?

**Comment by hernandev** [comment]
@pSchaub I don't personally use this because gzip compression is done on CDN side (Cloudflare), but for sure, it could be enabled on nginx, and be switched on and off with an environement variable.

if you need this right away, you may just replace the ngin.conf on your build process, including the gzip section.

I'll add this as a feature as soon as possible.

Thank you!

**Comment by hernandev** [comment]
Closing by inactivity. Thank you for using Ambientum! Be welcome to ask for help at any time.
